ALTER TABLE appointments
ADD COLUMN IF NOT EXISTS booking_code text,
ADD COLUMN IF NOT EXISTS note text,
ADD COLUMN IF NOT EXISTS reception_note text,
ADD COLUMN IF NOT EXISTS technician_note text,
ADD COLUMN IF NOT EXISTS source text DEFAULT 'MANUAL',
ADD COLUMN IF NOT EXISTS customer_booked boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS has_private_booking boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS discount numeric DEFAULT 0,
ADD COLUMN IF NOT EXISTS discount_note text,
ADD COLUMN IF NOT EXISTS service_total numeric DEFAULT 0,
ADD COLUMN IF NOT EXISTS tax_total numeric DEFAULT 0,
ADD COLUMN IF NOT EXISTS tip_total numeric DEFAULT 0,
ADD COLUMN IF NOT EXISTS grand_total numeric DEFAULT 0,
ADD COLUMN IF NOT EXISTS payment_status text DEFAULT 'UNPAID',
ADD COLUMN IF NOT EXISTS checked_in_at timestamptz,
ADD COLUMN IF NOT EXISTS actual_start_at timestamptz,
ADD COLUMN IF NOT EXISTS actual_end_at timestamptz,
ADD COLUMN IF NOT EXISTS created_by_staff_id text;